### ISSUE TITLE
NullPointerException when switching buffer in 2016.2

### ISSUE THREAD

**Issue by rdgoite** [MulgaSoft/intellemacs#10]
## Description

I recently upgraded to IDEA 2016.2. Every time I switch buffer via <kbd>C-x b</kbd> or <kbd>C-x C-b</kbd>, I get the following error:

```
java.lang.NullPointerException
    at com.mulgasoft.emacsplus.actions.wrapper.SwitchToBuffer.removeFromActions(SwitchToBuffer.java:184)
    at com.mulgasoft.emacsplus.actions.wrapper.SwitchToBuffer.keySetup(SwitchToBuffer.java:102)
    at com.mulgasoft.emacsplus.actions.wrapper.SwitchToBuffer.actionPerformed(SwitchToBuffer.java:60)
    at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:197)
    at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
    at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:156)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:211)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:587)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$2(IdeKeyEventDispatcher.java:634)
    at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:199)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:633)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inSecondStrokeInProgressState(IdeKeyEventDispatcher.java:356)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inWaitForSecondStrokeState(IdeKeyEventDispatcher.java:292)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:217)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:677)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
## Reproduction

This is how I got my system set up with Emacs+:
1. Install Emacs+ on IDEA 2016.1.
2. Upgrade to IDEA 2016.2 and import previous configuration.
3. Import or create a project, and some code (open at least 2 editors).
4. Switch buffers using <kbd>C-x b</kbd>
## System Specifications
- IDEA version: 2016.2
- Operating System: OS X 10.10.5 (Yosemite)
- Development environment: Java (8)
- Emacs+ version: 0.3.200

**Comment by ryankask** [comment]
I'm also seeing this error. From what I remember, the plugin is a bit tricky to maintain because the APIs are constantly changing. This is probably happening more frequently with the new Intellij release model.

It would be great to hear from @mfeber about the roadmap of this incredibly useful plugin.

**Comment by shoaniki** [comment]
Since there's been no response to these bug reports or mailing list questions for a while, I have taken the liberty of patching this bug (and #9 as well) by modifying the class files.  It's a trivial bug that is identical in both cases -- a call to `getClientProperty("AnAction.shortcutSet")` failing because in IDEA 2016.2 it needs to be `getClientProperty(AnAction.ACTION_KEY)` instead.

[Patch.zip](https://github.com/MulgaSoft/intellemacs/files/421200/Patch.zip) contains my modified class files, which you can add to your Emacs+.jar to apply the workaround.

**Comment by rdgoite** [comment]
@shoaniki Thank you very much. It's been bugging me that I can't use the latest version of IDEA because I can't operate well without this plugin. However, I have no experience patching class files directly, and, to be honest, I'm a little cautious (mainly due to lack of knowledge) about applying your changes. I hope you understand. If you have some extra time, could you share with us exactly how you did the fix?

**Comment by rdgoite** [comment]
A quick work around this issue is to re-map `C-x C-x` and/or `C-x b` to IDEA's built-in `Switcher` command from Emacs+'s `switch-to-buffer` command. To do this:
1. Open preferences (Intellij IDEA > Preferences).
2. Switch to `Keymap` tab/submenu.
3. Search for either "switch-to-buffer" using string search or control+x control+b keys using the key search.
4. Remove mapping. 
5. Search for "switcher" in the search box.
6. Add control+x control+b as a keyboard shortcut for the switcher command.
