### ISSUE TITLE
NoClassDefFound for recent EAP

### ISSUE THREAD

**Issue by matklad** [MulgaSoft/intellemacs#2]
:heart:  First of all, thanks a lot! This plugin is a pure awesomeness! :heart: 

I wish it is advertised more....

However, I got `NoClassDefFoundError` on the latest EAP, when I invoke `C-x b`.

Here is a stack trace

```
com/intellij/ide/actions/Switcher$MyList
java.lang.NoClassDefFoundError: com/intellij/ide/actions/Switcher$MyList
    at com.mulgasoft.emacsplus.actions.wrapper.SwitchToBuffer.keySetup(SwitchToBuffer.java:126)
    at com.mulgasoft.emacsplus.actions.wrapper.SwitchToBuffer.actionPerformed(SwitchToBuffer.java:60)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:595)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:646)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inSecondStrokeInProgressState(IdeKeyEventDispatcher.java:361)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inWaitForSecondStrokeState(IdeKeyEventDispatcher.java:297)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:221)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:617)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:380)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: com.intellij.ide.actions.Switcher$MyList PluginClassLoader[com.mulgasoft.emacsplus, 0.3.110]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 15 more
```

**Comment by mfeber** [comment]
EAP releases are not reliably supported as the codebase can gyrate pretty significantly from one EAP to the next.  Expect the plugin to work with (the then current) EAP on the next release.

**Comment by mfeber** [comment]
All should be well (except for https://youtrack.jetbrains.com/issue/IDEA-148316) in version 0.3.200.

**Comment by matklad** [comment]
> All should be well 

Yes, everythig works like a charm, thanks!

**Comment by matklad** [comment]
Hm, I've noticed that I still get a similar exception in IDEA 15.0.2, although the switcher works correctly. The stack trace is slightly different:

```
com/intellij/ide/actions/Switcher$MyList
java.lang.NoClassDefFoundError: com/intellij/ide/actions/Switcher$MyList
    at com.mulgasoft.emacsplus.actions.wrapper.SwitchToBuffer.keySetup(SwitchToBuffer.java:126)
    at com.mulgasoft.emacsplus.actions.wrapper.SwitchToBuffer.actionPerformed(SwitchToBuffer.java:60)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:595)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:646)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inSecondStrokeInProgressState(IdeKeyEventDispatcher.java:361)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inWaitForSecondStrokeState(IdeKeyEventDispatcher.java:297)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:221)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:622)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: com.intellij.ide.actions.Switcher$MyList PluginClassLoader[com.mulgasoft.emacsplus, 0.3.200]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 15 more
```

Plugin version is `0.3.200` (as can be seen from the stack trace)
