### ISSUE TITLE
StringIndexOutOfBounds for backwards kill word

### ISSUE THREAD

**Issue by matklad** [MulgaSoft/intellemacs#5]
If I `backwards-kill-word` the very first word in a file, I always get an exception. This also happens with `M-x`: `M-x foo M-DEL` -> `StringIndexOutOfRange: -1`

Stack trace

```
String index out of range: -1
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
    at java.lang.String.charAt(String.java:658)
    at com.intellij.openapi.editor.actions.EditorActionUtil.isHumpBound(EditorActionUtil.java:861)
    at com.intellij.openapi.editor.actions.EditorActionUtil.isWordStart(EditorActionUtil.java:269)
    at com.intellij.openapi.editor.actions.EditorActionUtil.isWordOrLexemeStart(EditorActionUtil.java:234)
    at com.intellij.openapi.editor.actions.KillToWordStartAction$Handler.executeWriteAction(KillToWordStartAction.java:53)
    at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler$1.run(EditorWriteActionHandler.java:56)
    at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1002)
    at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler.doExecute(EditorWriteActionHandler.java:49)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler$4.perform(EditorActionHandler.java:217)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:109)
    at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:214)
    at com.intellij.openapi.editor.actionSystem.EditorAction$1.run(EditorAction.java:98)
    at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
    at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:109)
    at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:83)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:595)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:646)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:485)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:215)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:617)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:380)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by mfeber** [comment]
The binding for backwards-kill-word does not currently actually change the internals, and what gets called is simply the IntelliJ version: EditorKillToWordStart, as you can see from your stack trace.  So,

1) Unable to reproduce
2) Evidence supplied points to (probably) an issue with your file/env (or less likely, an IntelliJ issue)

I'm not an exert at unscrewing a particular installation, but you could try **Invalidate Caches / Restart**, or removing all the subsidiary Idea1x directories and restarting.

Also, you didn't specify: platform/os, version of IntelliJ, version of Emacs+, language of the file being edited, etc.

**Comment by matklad** [comment]
Yes, this indeed is a bug in IDEA itself, thanks!
